### ISSUE TITLE
Package also extensions like xdebug

### ISSUE THREAD

**Issue by shyim** [fossar/nix-phps#172]
Hey,

I want to test PHP 8.2 with XDebug but the XDebug in Nixpkgs does not work yet. Maybe add extensions here too? 🤔

**Comment by drupol** [comment]
Good point, we should have done that.

PHP 8.2 is about to be included by default in Nix, see: https://github.com/NixOS/nixpkgs/pull/201000, I guess we should add XDebug in that PR.

**Comment by drupol** [comment]
Job done, enjoy !
