### ISSUE TITLE
Provide packages entry

### ISSUE THREAD

**Issue by shyim** [fossar/nix-phps#188]
In nixpkgs we have those php81Packages.<tool>. It would be nice if the output could have the same. Of course, not any tool will work.

Example package: `php74Packages.php-parallel-lint`

**Comment by jtojnar** [comment]
I do not really like having multiple ways to get the same attribute set and there already is `php74.pkgs.php-parallel-lint`. Ideally, we would remove `phpXYPackages` from Nixpkgs. Unfortunately, it is currently required for Hydra to be able to recurse into the attribute set.

**Comment by shyim** [comment]
```
❯ nix develop github:fossar/nix-phps#php74.pkgs.php-parallel-lint
error: flake 'github:fossar/nix-phps' does not provide attribute 'devShells.aarch64-darwin.php74.pkgs.php-parallel-lint', 'packages.aarch64-darwin.php74.pkgs.php-parallel-lint', 'legacyPackages.aarch64-darwin.php74.pkgs.php-parallel-lint' or 'php74.pkgs.php-parallel-lint'
       Did you mean args?

```

Don't seem to work 🤔

**Comment by drupol** [comment]
Try

```shell
nix develop github:fossar/nix-phps#php74.packages.php-parallel-lint
````

**Comment by shyim** [comment]
Works. 🎉 

Maybe add it too in README? Didn't know that PHP packages contain that too

**Comment by drupol** [comment]
I don't think it needs to be in the README, it's the same behavior as in `nixpkgs`, see: https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=php-parallel-lint

Maybe @jtojnar has another point of view.

**Comment by shyim** [comment]
it's fine for me. thanks anyway! :)
