### ISSUE TITLE
Update composer 2.2 LTS

### ISSUE THREAD

**Issue by DanielSiepmann** [fossar/nix-phps#224]
Composer for older PHP Versions is supported by 2.2 LTS. This is currently defined as 2.2.12. But current latest LTS is 2.2.21.

- https://github.com/fossar/nix-phps/blob/master/pkgs/composer/2.2.nix
- https://getcomposer.org/download/

Maybe we should update to latest LTS?

**Comment by drupol** [comment]
yes indeed we should!

Are you willing to provide the PR ?

**Comment by DanielSiepmann** [comment]
I can give it a try. I'm not used to flakes yet and am still a new user.

**Comment by drupol** [comment]
Here are the steps:

1. Fork and edit the file https://github.com/fossar/nix-phps/blob/master/pkgs/composer/2.2.nix
2. Update the version on line 4 and set the `sha256` to an empty string
3. Inside the same directory, run: `nix shell .#php71.packages.composer` at that point, it should print the updated `sha256`
4. Copy the new `sha256` where it was previously set to an empty string
5. Test: `nix run .#php71.packages.composer -- --version`
6. Submit your PR :)

**Comment by drupol** [comment]
`nix shell` or `nix run` would fail and display the proper sha anyway, so it's fine to use one or the other.
