### ISSUE TITLE
Failed to evaluate with latest nixpkgs as this overrides `callPackage`

### ISSUE THREAD

**Issue by moesoha** [fossar/nix-phps#310]
Because of [this nixpkgs commit](https://github.com/NixOS/nixpkgs/commit/c038b79502f379b1fe988520fc0d5f01c5799156) in php uses `callPackage`, and in your repo, [here](https://github.com/fossar/nix-phps/blob/8ec542b079458dfc65d802f9c2e3318887c1b785/pkgs/phps.nix#L91) overrides `callPackage` with adding two arguments. This will make `install-pear-nozlib-phar.nix` in nixpkgs failed to evaluate as:

```
       error: function 'anonymous lambda' called with unexpected argument 'pkgs'

       at /nix/store/9pbyw6i1aksn6l5ymm3fxldpsjvkjg4g-source/pkgs/development/interpreters/php/install-pear-nozlib-phar.nix:1:1:

            1| {
             | ^
            2|   fetchurl
```

**Comment by drupol** [comment]
Hi!

Thanks for reporting this.
Going to provide a fix today.

**Comment by drupol** [comment]
Besides reverting my commit in `nixpkgs`, I have no clue on how to fix this in here.

@jtojnar any clue?

**Comment by jtojnar** [comment]
Probably https://github.com/fossar/nix-phps/blob/9804430b760dadd414cc7457fc24e2c71713c168/pkgs/phps.nix#L106

**Comment by drupol** [comment]
I don't understand :(

**Comment by drupol** [comment]
@jtojnar Do you have another hint so I can fix this?

**Comment by jtojnar** [comment]
Maybe check if `cpArgs` contains `pkgs` and only `//` it then?

**Comment by drupol** [comment]
I couldn't find a way to get it working. Should I revert what I did in `nixpkgs` ?

**Comment by jtojnar** [comment]
If you wish. To be honest, I still do not see the point of the change in the first place.

**Comment by drupol** [comment]
The ideas behind that commit were:

1. Easily override `src`, without using `overrideAttrs`
2. Let `generic.nix` build PHP from the official `php-src` git repository 

I really wish to avoid reverting it because I still believe that change make sense.
If we revert that commit, we cannot build PHP from its sources(git), only from the distribution(php.net) and it would be really sad if we can't do that.

**Comment by jtojnar** [comment]
Well, I do not really mind `overrideAttrs`. But either way, the offending part of the commit is the pear thing, which is good idea IMO, and would cause issues even if we got rid of the `phpSrc` attribute.

The issue is really in [nix-phps](https://github.com/fossar/nix-phps/blob/9804430b760dadd414cc7457fc24e2c71713c168/pkgs/phps.nix#L106-L119).

I would try something like

```nix
cpArgs
            // lib.filterAttrs (key: _v: builtins.hasAttr cpArgs key) {...}
```

**Comment by drupol** [comment]
I tried, without luck :(

**Comment by jtojnar** [comment]
Other option might be something like 

```nix
(prev.callPackage cpFn cpArgs).override (prevArgs: lib.filterAttrs (key: _v: builtins.hasAttr (builtins.attrNames cpFn) prevArgs) {...})
```

**Comment by drupol** [comment]
Same issue as before:

```nix
callPackage =
        cpFn:
        cpArgs:

        (prev.callPackage cpFn cpArgs).override (prevArgs: prev.lib.filterAttrs (key: _v: builtins.hasAttr (builtins.attrNames cpFn) prevArgs) {
          pcre2 =
            if prev.lib.versionAtLeast args.version "7.3"
            then prev.pcre2
            else prev.pcre;

          # For passing pcre2 to stuff called with callPackage in php-packages.nix.
          pkgs =
            prev
            // (
              prev.lib.makeScope
                prev.newScope
                (self: {
                  pcre2 =
                    if prev.lib.versionAtLeast args.version "7.3"
                    then prev.pcre2
                    else prev.pcre;
                })
            );
        });
```

Error:

```
❯ nix build .#php80 -L
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'php-with-extensions-8.0.30'
         whose name attribute is located at /nix/store/mp4clz8rfv9vwl1n589kmkcp9k36ynkc-source/pkgs/stdenv/generic/make-derivation.nix:311:7

       … while evaluating attribute 'buildCommand' of derivation 'php-with-extensions-8.0.30'

         at /nix/store/mp4clz8rfv9vwl1n589kmkcp9k36ynkc-source/pkgs/build-support/trivial-builders/default.nix:87:14:

           86|       enableParallelBuilding = true;
           87|       inherit buildCommand name;
             |              ^
           88|       passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: value is a path while a set was expected
~/C/f/nix-phps > master +5 -10 [!?] ✘           
```
