### ISSUE TITLE
Add mac m1 cache

### ISSUE THREAD

**Issue by shyim** [fossar/nix-phps#322]
Finally we can add m1 runner cache to nix-phps with https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

Should be pretty easy to add that too

**Comment by drupol** [comment]
I did it already in loophp/nix-shell :)

It's just a one line change here as well.

I guess before doing that, we should fix the libxml builds issues... Sadly, I don't have a lot of time for open-source lately and I can't dedicate a lot of time to it :(
