### ISSUE TITLE
Is there a way to install Mcrypt extension for php5.6?

### ISSUE THREAD

**Issue by nick-kadutskyi** [fossar/nix-phps#337]
I am trying to configure an old project via devenv.sh and I see that they use this package for older php versions.
But I've tried to add Mcrypt extension and it says it's missing.

I am new to Nix and don't know how to handle this better but my assumption would be to create my own derivation for Mcrypt extension, build it and provide result to nix-phps so it can pass it further to php interpreter into withExtensions function? And then withExtensions function should handle adding the Mcrypt ext to php.ini file?

**Comment by drupol** [comment]
Hello,

I made a couple of PRs to add some missing extensions for PHP 5.6, maybe you can get some inspiration from them?

Here's a page listing a couple of commits where you can see them: https://github.com/fossar/nix-phps/pulls?page=3&q=is%3Apr+is%3Aclosed

Hope it helps.

**Comment by drupol** [comment]
I would suggest to use `buildPecl` to build that new extension you're trying to introduce.

I wish I could give more support, but I tend to limit the support I give to open-source these days because of some everyday life stuff.

Consider sponsoring this project or its maintainers to get a quicker personal support.

**Comment by nick-kadutskyi** [comment]
In the and I resolved it via this code:
```nix
{
  buildPecl,
  lib,
  fetchFromGitHub,
  libmcrypt,
  pkg-config,
}:

let
   version = "0.0.0";
   revision = "c37265eacdd0186cb3b0bfeb0e0104c8563807ef";
in
buildPecl {
  inherit version;

  pname = "mcrypt";

  src = fetchFromGitHub {
    owner = "php";
    repo = "php-src";
    rev = revision;
    sha256 = "sha256-aDiGbOqy2L8Qqd6IliEN19Oa8JO1uDSEju6uUN4b0XI=";
  } + "/ext/mcrypt";

  nativeBuildInputs = [ pkg-config ];
  buildInputs = [ libmcrypt ];

  configureFlags = [ "--with-mcrypt=${libmcrypt.outPath}" ];

  doCheck = true;
  checkTarget = "test";

  meta = {
    changelog = "https://github.com/php/php-src/commit/${revision}";
    description = "Mcrypt from 5.6.4";
  };
}
```
It gets PHP 5.6.4 and its mcrypt code and it works well together.

**Comment by drupol** [comment]
Good! You could also submit a PR against this project so it's available for everyone!

**Comment by nick-kadutskyi** [comment]
I've done it separately in the file but would definitely be cooler to get it from this project!
I'll try to do that tomorrow

**Comment by jtojnar** [comment]
Looks like it was moved to PECL https://www.php.net/manual/en/intro.mcrypt.php, https://pecl.php.net/package/mcrypt

**Comment by nick-kadutskyi** [comment]
@jtojnar I couldn't use anything from Pecl because their API version is different than PHP5.6 so I build the one being released together with PHP5.6 https://github.com/php/php-src/commit/c37265eacdd0186cb3b0bfeb0e0104c8563807ef

**Comment by nick-kadutskyi** [comment]
Added a pr for this https://github.com/fossar/nix-phps/pull/340
