### ISSUE TITLE
Override to instal a specific php version

### ISSUE THREAD

**Issue by hansemschnokeloch** [fossar/nix-phps#353]
How can I write an override to install a specific php version ?
For example I would like to downgrade to php 8.2.19 to avoid this bug https://github.com/api-platform/core/issues/6416

**Comment by drupol** [comment]
Hello,

You could override the `src` and download a custom version.

Alternatively, you can use this project: https://github.com/loophp/php-src-nix/
It strives to compile all the PHP tags available.
