### ISSUE TITLE
php 7.2 bz2 extension?

### ISSUE THREAD

**Issue by RusticCraftsman** [fossar/nix-phps#365]
Im using php 7.2 and i need the bz2 extension for my site, is there any chance it could get added to the extension list?

If that is not the case, how could i install it myself manually?

Thanks in advance

**Comment by jtojnar** [comment]
Please do not use this for public sites. PHP 7.2 provided here is insecure (#366)  and unmaintained and we only provide it for development purposes.

However, `bz2` is available and work justs fine with PHP 7.2.

If you wanted to have it included in the cache, you could do something like the following (without the change to `package-overrides.nix` and with different version bounds):

https://github.com/fossar/nix-phps/commit/5c2a9bf0246b7f38b7ca737f0f1f36d5b45ae15a

**Comment by jtojnar** [comment]
You can use the `withExtensions` function as described in the Nixpkgs manual:

https://nixos.org/manual/nixpkgs/stable/#ssec-php-user-guide-installing-with-extensions

**Comment by jtojnar** [comment]
It looks like that is indeed not packaged.

If you want the built-in `pdo_firebird`, it would need to be added here:

https://github.com/NixOS/nixpkgs/blob/107b787d201c792c41c2d716eecc480194b8b3fe/pkgs/top-level/php-packages.nix#L574-L578

If you mean https://github.com/FirebirdSQL/php-firebird, it would need to go to https://github.com/NixOS/nixpkgs/blob/107b787d201c792c41c2d716eecc480194b8b3fe/pkgs/top-level/php-packages.nix#L242

**Comment by jtojnar** [comment]
You would typically start by duplicating one of similar packages and then editing them until it builds. For example, you can start by copying the memcached line in your local Nixpkgs checkout:

https://github.com/NixOS/nixpkgs/blob/107b787d201c792c41c2d716eecc480194b8b3fe/pkgs/top-level/php-packages.nix#L286

Then copying the expression file

https://github.com/NixOS/nixpkgs/blob/107b787d201c792c41c2d716eecc480194b8b3fe/pkgs/development/php-packages/memcached/default.nix

And then updating it to fetch https://github.com/FirebirdSQL/php-firebird
